src/ShoppingCartBundle/Entity/Product.php
<?php

namespace ShoppingCartBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass="ShoppingCartBundle\Repository\ProductRepository")
 * @ORM\Table(name="product")
 * @Vich\Uploadable()
 */
class Product
{
    /**
     * @var int $id
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string $name
     *
     * @ORM\Column(type="string", unique=false, length=255)
     * @Assert\NotBlank()
     */
    private $name;

    /**
     * @var string $description
     *
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $description;

    /**
     * @var int
     *
     * @ORM\Column(type="integer")
     * @Assert\NotBlank()
     * @Assert\Range(min="0", max="5000")
     */
    private $quantity;

    /**
     * @var string $imageName
     *
     * @ORM\Column(type="string", length=255)
     */
    private $imageName;
    /**
     * @var File $imageFile
     *
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="imageName")
     * @Assert\NotNull(groups={"NewProduct"}, message="You should upload a product image.")
     * @Assert\Image()
     */
    private $imageFile;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="ShoppingCartBundle\Entity\Category", inversedBy="products",  fetch="EXTRA_LAZY")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id", onDelete="CASCADE")
     * @Assert\NotBlank()
     */
    private $category;

    /**
     * @var double $price
     *
     * @ORM\Column(type="decimal", precision=10, scale=2)
     * @Assert\NotBlank()
     * @Assert\Range(min="0.01", max="900000")
     */
    private $price;

    /**
     * @var string $slug
     *
     * @ORM\Column(nullable=false, type="string", unique=true)
     * @Gedmo\Slug(fields={"name"})
     */
    private $slug;

    /**
     * @var bool $isListed
     *
     * @ORM\Column(type="boolean")
     */
    private $isListed;

    /**
     * @var Review[]|ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="ShoppingCartBundle\Entity\Review", mappedBy="product")
     */
    private $reviews;

    /**
     * @var Promotion[]|ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="ShoppingCartBundle\Entity\Promotion", inversedBy="products")
     * @ORM\JoinTable(name="product_promotions")
     * @ORM\OrderBy({"discount" = "DESC"})
     */
    private $promotions;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="ShoppingCartBundle\Entity\User", inversedBy="myProducts")
     */
    private $seller;

    /**
     * @var User
     *
     * @ORM\ManyToMany(targetEntity="ShoppingCartBundle\Entity\User", mappedBy="cart")
     * @ORM\JoinTable(name="users_carts")
     */
    private $userCart;

    /**
     * @var bool $isReseller
     *
     * @ORM\Column(type="boolean")
     */
    private $isResold;

    public function __construct()
    {
        $this->reviews = new ArrayCollection();
        $this->promotions = new ArrayCollection();
        $this->createdAt = new \DateTime();
        $this->isResold = false;
    }

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName($name)
    {
        $this->name = $name;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @param string $description
     */
    public function setDescription($description)
    {
        $this->description = $description;
    }

    /**
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * @param int $quantity
     */
    public function setQuantity($quantity)
    {
        $this->quantity = $quantity;
    }

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param Category $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }

    /**
     * @return float
     */
    public function getPrice()
    {
        if (!$this->hasActivePromotion()) {
            return $this->price;
        }

        $discount = $this->price * $this->getBiggestActivePromotion()->getDiscount() / 100;
        return $this->price - $discount;
    }

    /**
     * @param float $price
     */
    public function setPrice($price)
    {
        $this->price = $price;
    }

    /**
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param string $slug
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    }

    /**
     * @return bool
     */
    public function isListed()
    {
        return $this->isListed;
    }

    /**
     * @param bool $isListed
     */
    public function setIsListed($isListed)
    {
        $this->isListed = $isListed;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;
    }

    /**
     * @return string
     */
    public function getImageName()
    {
        return $this->imageName;
    }

    /**
     * @param string $imageName
     */
    public function setImageName($imageName)
    {
        $this->imageName = $imageName;
    }

    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;
    }

    /**
     * @return ArrayCollection|Review[]
     */
    public function getReviews()
    {
        return $this->reviews;
    }

    /**
     * @param ArrayCollection|Review[] $reviews
     */
    public function setReviews($reviews)
    {
        $this->reviews = $reviews;
    }

    /**
     * @return float
     */
    public function getOriginalPrice()
    {
        return $this->price;
    }

    /**
     * @return ArrayCollection|Promotion[]
     */
    public function getPromotions()
    {
        return $this->promotions;
    }

    /**
     * @param ArrayCollection|Promotion[] $promotions
     */
    public function setPromotions($promotions)
    {
        $this->promotions = $promotions;
    }

    /**
     * @return User
     */
    public function getSeller()
    {
        return $this->seller;
    }

    /**
     * @param User $seller
     */
    public function setSeller($seller)
    {
        $this->seller = $seller;
    }

    /**
     * @return int
     */
    public function getAverageRating(): int
    {
        if (count($this->getReviews()) > 0) {
            $sum = array_reduce($this->getReviews()->toArray(), function ($sum, Review $review) {
                $sum += $review->getRating();

                return $sum;
            });

            return floor($sum / count($this->getReviews()));
        }

        return 0;
    }

    /**
     * @return bool
     */
    public function hasActivePromotion()
    {
        if ($this->getBiggestActivePromotion()) {
            return true;
        }
        return false;
    }

    /**
     * @return null|Promotion
     */
    public function getBiggestActivePromotion()
    {
        return $this->promotions->filter(function (Promotion $promotion) {
            return $promotion->isActive();
        })->first();
    }

    /**
     * @param Promotion $promotion
     */
    public function addPromotion(Promotion $promotion)
    {
        $this->promotions->add($promotion);
    }

    /**
     * @param Promotion $promotion
     */
    public function removePromotion(Promotion $promotion)
    {
        $this->promotions->removeElement($promotion);
    }

    /**
     * @return bool
     */
    public function isResold()
    {
        return $this->isResold;
    }

    /**
     * @param bool $isResold
     */
    public function setIsResold($isResold)
    {
        $this->isResold = $isResold;
    }

    /**
     * @return bool
     */
    public function isInStock(): bool
    {
        return $this->quantity > 0;
    }
}

src/ShoppingCartBundle/Controller/Admin/UsersController.php
<?php

namespace ShoppingCartBundle\Controller\Admin;

use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use ShoppingCartBundle\Entity\User;
use ShoppingCartBundle\Form\UserAddEditForm;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;


/**
 * Class UsersController
 * @package ShoppingCartBundle\Controller
 *
 * @Route("/admin")
 * @Security("is_granted('ROLE_ADMIN')")
 */
class UsersController extends Controller
{

    /**
     * @Route("/users/all", name="admin_users_all")
     * @Method("GET")
     *
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     */
    public function allUsersAction(Request $request,PaginatorInterface $paginator): Response
    {
        $users = $paginator->paginate(
            $this->getDoctrine()->getRepository(User::class)
                ->findAllByQueryBuilder(),
            $request->query->getInt('page', 1),
            10
        );;

        return $this->render("ShoppingCartBundle:admin/users:all.html.twig", [
            "users" => $users
        ]);
    }

    /**
     * @Route("/users/add", name="admin_users_add")
     *
     * @param Request $request
     * @return Response
     */
    public function addUserAction(Request $request): Response
    {
        $form = $this->createForm(UserAddEditForm::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->persist($user);
            $em->flush();

            $this->addFlash("success", "User {$user->getFullName()} added successfully!");

            return $this->redirectToRoute('admin_users_all');
        }

        return $this->render('@ShoppingCart/admin/users/add.html.twig', [
            "add_form" => $form->createView()
        ]);
    }

    /**
     * @Route("/users/delete/{id}", name="admin_users_delete")
     *
     * @return Response
     */
    public function deleteUserAction(User $user): Response
    {
        if ($user->getMyProducts()->count() > 0) {
            $this->addFlash(
                "danger", "You cant delete user which has products! You can ban his account!");
        } else {
            $em = $this->getDoctrine()->getManager();
            $em->remove($user);
            $em->flush();
            $this->addFlash("success", "User with username {$user->getEmail()} deleted successfully!");
        }
        return $this->redirectToRoute('admin_users_all');
    }

    /**
     * @Route("/users/edit/{id}", name="admin_users_edit")
     *
     * @param Request $request
     * @param User $user
     * @return Response
     */
    public function editUserAction(Request $request, User $user): Response
    {
        $form = $this->createForm(UserAddEditForm::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            $em = $this->getDoctrine()->getManager();
            $em->flush();

            $this->addFlash("success", "User {$user->getFullName()} edited successfully!");

            return $this->redirectToRoute('admin_users_all');
        }

        return $this->render('@ShoppingCart/admin/users/edit.html.twig', [
            "edit_form" => $form->createView()
        ]);
    }

    /**
     * @Route("/users/ban/{id}", name="admin_users_ban")
     *
     * @param User
     * @return Response
     */
    public function banUserAction(User $user): Response
    {
        $em = $this->getDoctrine()->getManager();
        if ($user->isBanned()) {
            $this->addFlash("error", "User with username {$user->getEmail()} is already banned!");

            return $this->redirectToRoute('admin_users_all');
        }

        $user->setIsBanned(true);
        $em->flush();

        $this->addFlash("success", "User with username {$user->getEmail()} is banned!");
        return $this->redirectToRoute('admin_users_all');
    }

    /**
     * @Route("/users/unban/{id}", name="admin_users_unban")
     *
     * @param User
     * @return Response
     */
    public function unBanUserAction(User $user): Response
    {
        $em = $this->getDoctrine()->getManager();
        if (!$user->isBanned()) {
            $this->addFlash("error", "User with username {$user->getEmail()} is already not banned!");

            return $this->redirectToRoute('admin_users_all');
        }

        $user->setIsBanned(false);
        $em->flush();

        $this->addFlash("success", "User with username {$user->getEmail()} is is unlocked / not banned!");
        return $this->redirectToRoute('admin_users_all');
    }
}

src/ShoppingCartBundle/Resources/views/users/edit.html.twig
{% extends "@ShoppingCart/base.html.twig" %}

{% block body %}
    {{ form_start(edit_form) }}

    {{ form_row(edit_form.fullName) }}

    {{ form_row(edit_form.plainPassword.first, {
        label: "New Password"
    }) }}
    {{ form_row(edit_form.plainPassword.second, {
        label: "Repeat New Password"
    }) }}
    <hr>
    <button class="btn btn-primary fa fa-thumbs-up" formnovalidate>Edit</button>

    {{ form_end(edit_form) }}
{% endblock %}

src/ShoppingCartBundle/Resources/views/users/login.html.twig
{% extends "@ShoppingCart/base.html.twig" %}

{% block body %}
    {% if error %}
        <div class="alert alert-danger">
            {{ error.messageKey|trans(error.messageData, 'security') }}
        </div>
    {% endif %}
    <div class="container body-content span=8 offset=2">
        <div class="well">
            {{ form_start(login_form) }}

            {{ form_row(login_form._username) }}
            {{ form_row(login_form._password) }}

            <button type="submit" class="btn btn-primary fa fa-thumbs-up" formnovalidate>Login</button>
        </div>
    </div>
{% endblock %}

src/ShoppingCartBundle/Resources/views/users/profile.html.twig
{% extends "@ShoppingCart/base.html.twig" %}

{% block body %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Profile details:</h3>
        </div>
        <div class="panel-body">
            <table class="table table-responsive">
                <tr>
                    <th>Email</th>
                    <td>{{ user.email }}</td>
                </tr>
                <tr>
                    <th>Name</th>
                    <td>{{ user.fullName }}</td>
                </tr>
                <tr>
                    <th>Roles</th>
                    <td>{{ user.roles|join(", ") }}</td>
                </tr>
                <tr>
                    <th>Money</th>
                    <td><strong>€{{ user.money }}</strong></td>
                </tr>
            </table>
            <a class="btn-info btn fa fa-thumbs-up" href="{{ path('user_profile_edit') }}">Edit</a>
        </div>
    </div>

{% endblock %}

src/ShoppingCartBundle/Resources/views/users/register.html.twig
{% extends "@ShoppingCart/base.html.twig" %}

{% block body %}
    <div class="container body-content span=8 offset=2">
        <div class="well">
            {{ form_start(register_form) }}

            {{ form_row(register_form.email) }}
            {{ form_row(register_form.fullName) }}
            {{ form_row(register_form.plainPassword.first, {
                label: "Password"
            }) }}
            {{ form_row(register_form.plainPassword.second, {
                label: "Repeat Password"
            }) }}

            <button class="btn btn-primary fa fa-thumbs-up" formnovalidate>Register</button>

            {{ form_end(register_form) }}
        </div>
    </div>
{% endblock %}

src/ShoppingCartBundle/Resources/views/users/user_shop_page.html.twig
{% extends '@ShoppingCart/base.html.twig' %}

{% block body %}
    <h2 class="text-center">Welcome to {{ seller.fullName }} shop!</h2>
    <hr>
    {% if products|length > 0 %}
        <div class="row">
        {% for index, product in products %}
            {% if index % 3 == 0 and index > 0 %}
                </div>
                <div class="row">
            {% endif %}
            {% include '@ShoppingCart/users/user_shop_product_thumb.html.twig' %}
        {% endfor %}
        </div>
        <div class="navigation text-center">
            {{ knp_pagination_render(products) }}
        </div>
    {% else %}
        <h3>This user has no products for sale at this moment :(</h3>
    {% endif %}
{% endblock %}

src/ShoppingCartBundle/Resources/views/users/user_shop_product_thumb.html.twig
<div class="col-sm-6 col-md-4">
    <div class="thumbnail fixed-div">
        <h3 class="text-center">{{ product.name }}</h3>
        <img class="img-thumbnail center-block fixed-image" src="{{ vich_uploader_asset(product, "imageFile") }}"
             alt="{{ product.name }}">
        <div class="caption">
            <div class="text-center">
                {{ product.averageRating|starsRating|raw }}
                <h5 class="label-info">Selled by: {{ product.seller.fullname }}</h5>
            </div>
            <hr>
            <p><strong>Category</strong><a
                        href="{{ path('show_products_by_category', {'slug': product.category.slug}) }}">
                    {{ product.category.name }}
                </a></p>
            <p><strong>Quantity available: {{ product.quantity }}</strong></p>
            <div class="h3">
                <span class="label label-info">€{{ product.price|number_format(2) }}</span>
            </div>
            <hr>
            <p class="text">
            <form method="post" style="display: inline-block">
                <a href="{{ path("cart_add", {"slug": product.slug}) }}" class="btn btn-primary"
                   role="button"><i class="fa fa-cart-plus" aria-hidden="true"> Add to Cart</i></a>
            </form>
            <a href="{{ path("product_show", {"slug": product.slug}) }}" class="btn btn-default"
               role="button"><i class="fa fa-info" aria-hidden="true"> Details</i>
            </a>
        </div>
    </div>
</div>